services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - request

  postgres:
    image: postgres:14-alpine
    ports:
      - '5433:5432'
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - request

networks:
  request:

volumes:
  postgres-data:
